### ISSUE TITLE
Queries break after 60sec (open or openLazy)

### ISSUE THREAD

**Issue by seankndy** [clue/reactphp-sqlite#29]
After 60 seconds of idle time, queries fail (silently).

I noticed some documentation in the README stating after 60sec, the openLazy connection closes, but automatically reopens on the following query.  I am not seeing that function, though. What happens is after 60sec, query() is called and it returns a promise, but that promise isn’t resolving or rejecting ( the anon functions I have for handlers never get called either way ) and the query (which happens to be an INSERT) never actually happens.

I also noticed that for each successive query after the initial 60sec idle period, an sqlite-worker.php is added to the system process list and seems to never end.  So it appears that workers are getting 'stuck'.

I also tried using open() instead of openLazy() and calling open() before every query (and a  $db->quit() when it finishes).  The behavior is the same -- the first query works, successive ones fail so long as the successive queries are >60sec since the successful one.

I am using Mac OS 10.15.4 and running PHP 7.4.0.  child-process v0.6.1, reactphp-sqlite v1.0.1, react/event-loop v1.1.1.

**Comment by clue** [comment]
@seankndy Thanks for reporting, this should not have happened!

This should already be covered by the test suite and I can not currently reproduce the problem you're seeing locally. Perhaps this could be related to your specific platform (settings)? Can you try seeing if the test suite executes fine on your platform?

That being said, your error description sounds a bit *surprising*. The `openLazy()` will indeed use a 60s idle timer to close unused connections by default. This can be controlled via `$db = $factory->openLazy('users.db', null, ['idle' => 0.1]);`, perhaps you can give this a try? The underlying `open()` method does not use any such timer and as such I don't see anything that would cause similar behavior here.

Perhaps you can change some of these settings and come up with a short gist to reproduce this problem?

**Comment by clue** [comment]
Ping @seankndy, can you update the status here? :+1:

**Comment by seankndy** [comment]
I was able to run all the unit tests on my machine successfully. In addition, I am not able to reproduce this issue any longer.  I don't know what exactly has changed, but if I run into this again I'll reopen the issue.  Thanks for your attentiveness.

**Comment by clue** [comment]
@seankndy Thanks for the update and happy to hear this has been resolved either way :+1:
