### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError:

### ISSUE THREAD

**Issue by sir-reynolds** [clue/reactphp-sqlite#40]
i try code on [example insert](https://github.com/clue/reactphp-sqlite/blob/master/examples/insert.php) and run from cli 
php react-sqlite.php 50, and this is error information

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Clue\React\SQLite\Factory::__construct(), 0 passed in C:\laragon\www\php-composer-lib\react-sqlite.php on line 8 and exactly 1 expected in C:\laragon\www\php-composer-lib\vendor\clue\reactphp-sqlite\src\Factory.php:29
Stack trace:
#0 C:\laragon\www\php-composer-lib\react-sqlite.php(8): Clue\React\SQLite\Factory->__construct()
#1 {main}
  thrown in C:\laragon\www\php-composer-lib\vendor\clue\reactphp-sqlite\src\Factory.php on line 29
```

information : 

> windows 10
> Laragon
> php 7.2.19

**Comment by clue** [comment]
@sir-reynolds It looks like you're using the documentation/examples from the current `main` version while running the `v1.1.0` release. Your above code should work against the current `main` version and the upcoming `v1.2.0` release version (#39) :+1:
