### ISSUE TITLE
Support to issue initial queries

### ISSUE THREAD

**Issue by hvt** [clue/reactphp-sqlite#67]
Hey there, neat idea to make DB access async by using UNIX sockets and a separate process.

I was wondering about something in regard to this. I'm using the `LazyDatabase` primitive, to minimize opening the database when nothing is actually queried.

In regard to SQLite, most of the times I'm using the [WAL mode](https://www.sqlite.org/wal.html#activating_and_configuring_wal_mode). But I find it a hassle to bother a user of the `DatabaseInterface` to always issue the `PRAGMA journal_mode=wal` query first, before querying anything else.

So is there any other way to enable the WAL mode? Is it perhaps possible to adapt the `journal_mode` using any of the `$flags`? (I could not find much information what flags are available.)

If that's not the case, I guess emitting an `open` event when the connection was actually opened -- with the `DatabaseInterface` instance as the event's first argument -- would really help.

In that case one could:

```php
$db->on('open', function(DatabaseInterface $db) {
    $db->exec('PRAGMA journal_mode=wal;'));
});
```

**Comment by hvt** [comment]
(I have to admit that TIL that setting the journal mode to WAL [is a persistent setting](https://www.sqlite.org/wal.html#persistence_of_wal_mode). So the initial query I imagined I needed, is not needed anymore. But still, would like to discuss how one would issue initial queries using this wonderful library :).)

**Comment by SimonFrings** [comment]
Hey @hvt, thank you for taking the time and bringing in your ideas to improve this project :+1:

There's actually an open feature request for this in #27. In there @clue described how a future `SqliteClient` concept could look like (#47), pretty similar to what you're suggesting:

```php
$db = new Clue\React\Sqlite\SqliteClient('users.db');

$db->on('open', fn () => $db->exec('PRAGMA foreign_keys = on'));

$db->query('SELECT 1')->then(fn (QueryResult $result) => var_dump($result));
```

At the moment, we don't have any specific plans for when this will go live and as a result, I'm unable to provide you with an estimated timeline for its introduction in this project. @clue and I are working on a lot of different open source projects with the focus on ReactPHP and Framework X, so we'll keep you posted once we find the time to look into this :+1:

If you need this urgently, you can also reach out to us or help us by [becoming as sponsor](https://github.com/sponsors/reactphp) ❤️

**Comment by hvt** [comment]
Hey @SimonFrings, sorry I did not find the feature request #27, but that was indeed exactly what I need.

I'm good for now, did some ugly facading, so I just wait for the next good release to arrive.

Bon boyage on all the ReactPHP & Framework X stuff :+1:
